# TRMNLP configuration
---
watch:
  - .trmnlp.yml
  - src

custom_fields:
  api_token: '{{ env.GITHUB_API_TOKEN }}'
  username: 'abs3ntdev'
  repo_owner: 'oku-trade'
  repo_name: 'trade'
  label: 'ready-to-merge'
variables: {}
trmnl: {}
